version: "3.8"

networks:
  proxy:
    external: true

services:
  whoami:
    image: traefik/whoami
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=Host(`branch.gustavomtborges.com`)"
    networks:
      - proxy

  whoami2:
    image: traefik/whoami
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami2.rule=Host(`qa.gustavomtborges.com`)"
    networks:
      - proxy
